# Generated by Django 2.0 on 2018-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpurchase',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='cashpurchasereturn',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='creditpurchasereturn',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
