# Generated by Django 2.0.6 on 2018-07-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0001_initial'),
        ('pop', '0003_auto_20180725_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpurchase',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='cashpurchase',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='cashpurchasereturn',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='cashpurchasereturn',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='creditpurchasereturn',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='creditpurchasereturn',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
    ]
