# Generated by Django 2.0.6 on 2018-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0004_auto_20180730_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpurchase',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashpurchasereturn',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditpurchasereturn',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
