# Generated by Django 2.2.3 on 2019-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnreceipt',
            name='number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnreceipt',
            name='number',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
