# Generated by Django 2.0 on 2018-02-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20180218_0727'),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='currency',
            field=models.CharField(blank=True, default='GHC', max_length=64),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='system',
            field=models.CharField(blank=True, default='Physical Cash', max_length=256),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash'),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='currency',
            field=models.CharField(blank=True, default='GHC', max_length=64),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='system',
            field=models.CharField(blank=True, default='Physical Cash', max_length=256),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='currency',
            field=models.CharField(blank=True, default='GHC', max_length=64),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='system',
            field=models.CharField(blank=True, default='Physical Cash', max_length=256),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash'),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='currency',
            field=models.CharField(blank=True, default='GHC', max_length=64),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='system',
            field=models.CharField(blank=True, default='Physical Cash', max_length=256),
        ),
    ]
