# Generated by Django 2.0 on 2018-02-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20180218_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
