# Generated by Django 2.0 on 2018-02-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_auto_20180219_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='purchasereturnreceipt',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='salesreceipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salesreturnreceipt',
            name='customer',
        ),
    ]
