# Generated by Django 2.0 on 2018-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_auto_20180219_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
