# Generated by Django 2.0.6 on 2018-07-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0001_initial'),
        ('receipt', '0005_auto_20180220_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='purchasereturnreceipt',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='salesreturnreceipt',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
    ]
