# Generated by Django 2.0 on 2018-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('BUSSINESS', 'Bussiness')], max_length=16, null=True),
        ),
    ]
