# Generated by Django 2.0.6 on 2018-07-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('domain', models.CharField(db_index=True, max_length=256, null=True)),
                ('subdomain', models.CharField(db_index=True, max_length=256)),
                ('subdomain_hash', models.CharField(db_index=True, max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BussinessBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('branch_hash', models.CharField(db_index=True, max_length=256)),
                ('renewed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness')),
            ],
        ),
    ]
