# Generated by Django 2.2.4 on 2019-08-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydecrement',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='inventoryincrement',
            name='comment',
        ),
    ]
