# Generated by Django 2.2.4 on 2019-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190831_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydecrement',
            name='comment',
            field=models.CharField(default='Decrease', max_length=256),
        ),
        migrations.AddField(
            model_name='inventoryincrement',
            name='comment',
            field=models.CharField(default='Increase', max_length=256),
        ),
    ]
