# Generated by Django 2.2.4 on 2019-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256)),
                ('amount', models.PositiveSmallIntegerField()),
                ('is_general', models.BooleanField(default=False)),
            ],
        ),
    ]
