# Generated by Django 2.0 on 2018-02-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cashsalesreturn',
            name='customer',
        ),
        migrations.AddField(
            model_name='cashsale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='cashsalesreturn',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
