# Generated by Django 2.0 on 2018-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20180219_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='creditsalesreturn',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
