# Generated by Django 2.2.4 on 2019-08-21 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='419', max_length=32)),
                ('settled', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20)),
                ('terms', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=256)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='419', max_length=32)),
                ('settled', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20)),
                ('terms', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=256)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='419', max_length=32)),
                ('settled', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20)),
                ('terms', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=256)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salesinvoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.SalesInvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='419', max_length=32)),
                ('settled', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20)),
                ('terms', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=256)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchasesinvoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.PurchaseInvoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
