# Generated by Django 2.0 on 2018-02-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20180220_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='settled',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='purchasereturninvoice',
            name='settled',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='settled',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='salesreturninvoice',
            name='settled',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20),
        ),
    ]
