# Generated by Django 2.0.6 on 2018-07-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0001_initial'),
        ('invoice', '0003_auto_20180220_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='purchasereturninvoice',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='purchasereturninvoice',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
        migrations.AddField(
            model_name='salesreturninvoice',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.BussinessBranch'),
        ),
        migrations.AddField(
            model_name='salesreturninvoice',
            name='bussiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Bussiness'),
        ),
    ]
